package fpt.signature.sign.everification.core;

enum TypeSig {
    SIGNATURE,
    SIGNATURE_NO_CHANGES_ALLOWED,
    CERTIFIED_NO_CHANGES_ALLOWED,
    CERTIFIED_FORM_FILLING_SIGNING,
    CERTIFIED_FORM_FILLING_SIGNING_COMMENTING;
}
